name: pgeon-dev
channels:
  - conda-forge
dependencies:
  # required
  # - python=3.10
  - pyarrow>=7.0
  - libpq

  # The compiler packages are meta-packages and install the correct compiler (activation) packages on the respective platforms.
  - c-compiler
  - cxx-compiler
  - cython
  - make
  - cmake
  - ninja
  - git

  # code checks
  - cpplint

  # testing
  - postgresql
  - asyncpg
  - pandas
  - jinja2
  - pytest
  - pytest-cov
  - pytest-xdist
