name: pgeon-dev
channels:
  - conda-forge
dependencies:
  # required
  # - python=3.10
  - pyarrow>=7.0
  - libpq

  # The compiler packages are meta-packages and install the correct compiler (activation) packages on the respective platforms.
  - c-compiler
  - cxx-compiler
  - cython
  - make
  - cmake
  - ninja
  - git

  # code checks
  - black
  - cpplint
  - flake8
  - flake8-bugbear  # used by flake8, find likely bugs
  - flake8-comprehensions  # used by flake8, linting of unnecessary comprehensions
  - isort  # check that imports are in the right order
  - mypy
  - pre-commit
  - pycodestyle  # used by flake8
  - pyupgrade

  # jupyter
  # - jupyter
  # - ipykernel
  # - ipywidgets

  # testing
  - postgresql
  - asyncpg
  - pandas
  - jinja2
  - pytest
  - pytest-cov
  - pytest-xdist