[build-system]
requires = [
  "setuptools>=45",
  "setuptools_scm[toml]>=6.2",
  "scikit-build",
  "pybind11",
  "cmake",
  "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
