[build-system]
requires = [
  "setuptools>=45",
  "setuptools_scm[toml]>=6.2",
  "scikit-build",
  "pybind11",
  "cmake",
  "ninja",
  "pyarrow"
]
build-backend = "setuptools.build_meta"

[project]
name = "pgeon"
description = "Apache Arrow PostgreSQL connector"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["arrow", "postgresql"]
license = { text = "MIT License" }
classifiers = [
  "Framework :: Apache Arrow",
  "Framework :: PostgreSQL",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Topic :: Database",
]
dynamic = ["version"]
dependencies = ["pyarrow"]

[project.optional-dependencies]
tests = ["psycopg[binary]", "pytest", "pytest-benchmark[histogram]"]

[tool.setuptools_scm]

[tool.cibuildwheel]
build = "cp39-* cp310-* cp311-*"
skip = "*_i686 *-musllinux_*"
build-verbosity = 2

[tool.cibuildwheel.linux]
before-build = "bash scripts/linux/prepare-build.sh" 
repair-wheel-command = "bash scripts/linux/repair-wheel.sh {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
before-build = "bash scripts/macos/prepare-build.sh" 
repair-wheel-command = "bash scripts/macos/repair-wheel.sh {dest_dir} {wheel} {delocate_archs}"
